# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-02 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160601_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tideentry',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
