# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-09 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_regionalforecast_regionalforecastentry_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localforecastentry',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
