# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-26 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160710_1813'),
        ('api', '0006_auto_20160609_1647'),
    ]

    operations = [
    ]
