# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-26 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Warning',
            new_name='WaveWarning',
        ),
    ]
