# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160824_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='wavewarning',
            name='subtitle',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
