# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_wavewarning_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wavewarning',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
