# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20160828_2126'),
        ('api', '0013_remove_localforecastentry_text'),
    ]

    operations = [
    ]
