# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_localforecastentry_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalForecastEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('animation_url', models.CharField(max_length=200)),
                ('regional_forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RegionalForecast')),
            ],
        ),
    ]
