# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-11 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_regionalforecastentry'),
        ('api', '0013_auto_20160828_2126'),
    ]

    operations = [
    ]
