# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_tideentry_moon'),
        ('api', '0015_merge'),
    ]

    operations = [
    ]
