# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionalforecastentry',
            name='regional_forecast',
        ),
        migrations.RemoveField(
            model_name='regionalforecast',
            name='large_icon_url',
        ),
        migrations.RemoveField(
            model_name='regionalforecast',
            name='medium_icon_url',
        ),
        migrations.RemoveField(
            model_name='regionalforecast',
            name='small_icon_url',
        ),
        migrations.AddField(
            model_name='regionalforecast',
            name='scale_bar_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regionalforecast',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='RegionalForecastEntry',
        ),
    ]
