# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-09 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20160915_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='localforecast',
            name='taxonomy_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
