# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-09 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20161009_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalforecast',
            name='taxonomy_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
