# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_regionalforecast_taxonomy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tideregion',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
