# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-04 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_tideregion_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='localforecast',
            name='region_map_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
