# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-18 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_tideregion_medium_level'),
        ('api', '0022_localforecast_region_map_url'),
    ]

    operations = [
    ]
