# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-18 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideForecastImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('url', models.CharField(max_length=400)),
                ('forecast_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RegionalForecast')),
            ],
        ),
    ]
