# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-08 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20170829_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='LocalForecastTranslation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wind_text', models.TextField()),
                ('wave_text', models.TextField()),
                ('temp_text', models.TextField()),
                ('salt_text', models.TextField()),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast', to='api.LocalForecast')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='api.Language')),
            ],
        ),
    ]
